const ACTION_TYPES = {
    ADD_TASK: 'ADD_TASK',
    VIEW_TASK: 'VIEW_TASK',
    DELETE_TASK: 'DELETE_TASK',
    INPUT_TASK_FORM: 'INPUT_TASK_FORM',

    SET_LOADING: 'SET_LOADING'
};

export default { ACTION_TYPES };